import type { Metadata } from "next";
import { Pacifico } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { GlobalEventsProvider } from "@/common/providers/globalEventsProvider";
import { ReactQueryProvider } from "@/common/providers/reactQueryProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pacifico",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <ReactQueryProvider>
        <GlobalEventsProvider />

        <html lang={locale}>
          <body
            className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased`}
          >
            <AntdRegistry>{children}</AntdRegistry>
          </body>
        </html>
      </ReactQueryProvider>
    </NextIntlClientProvider>
  );
}
